cwlVersion: v1.2
class: Workflow
label: "Expression Quantification Workflow"
doc: "A CWL workflow that performs expression quantification, currently only with HTSeq Count."

inputs:
    bamFiles:
        type: File[]
        doc: "The input BAM files."
    referenceGtf:
        type: File
        doc: "A GTF/GFF file containing the features of interest."
    detectNovelTranscripts:
        type: boolean
        doc: "If true, generates a new GTF from BAM files using StringTie. When a reference GTF is provided, it guides the assembly."
    strandedness:
        type: string
        doc: "The strandedness of the RNA sequencing library preparation. One of 'None' (unstranded), 'FR' (forward-reverse: first read equal transcript) or 'RF' (reverse-forward: second read equals transcript)."
    outputDir:
        type: string
        default: "."
        doc: "The output directory."

outputs:
    outputDir:
        type: Directory[]?
        outputSource:
            - flatOutputDir/flatArray
        doc: "The output directory."
    looseTables:
        type: File[]?
        outputSource:
            - flatCounts/flatArray
        doc: "All HTSeq produced tables, uncombined."
    outputTable:
        type: File?
        outputSource: 
            - collectCounts/outputTable
        doc: "Complete read count table generated by HTSeq, as formatted with collect columns."

requirements:
    InlineJavascriptRequirement: {}
    ScatterFeatureRequirement: {}
    StepInputExpressionRequirement: {}

steps:
    HTSeqCount:
        in:
            inputBams:
                source: bamFiles
                valueFrom: $([self])
            gtfFile: referenceGtf
            stranded: 
                source: strandedness
                valueFrom: "$(self === 'FR' ? 'yes' : self === 'RF' ? 'reverse' : 'no')"
            outputTable: 
                valueFrom: $(inputs.inputBams.basename.split(".")[0] + '.fragments_per_gene')
            outputDir:
                source: outputDir
                valueFrom: $(self + '/fragments_per_gene')
        out: [counts, outputDir]
        run: ../../tools/htseq-count_v0_12_4.cwl
        scatter: inputBams
        when: $(!inputs.detectNovelTranscripts) 
    flatCounts:
        in:
            inputData: HTSeqCount/counts
        out: [flatArray]
        run: ../../tools/array_flatten.cwl
        when: $(!inputs.detectNovelTranscripts)
    collectCounts:
        in: 
            inputTables: flatCounts/flatArray
            outputFile:
                valueFrom: "all_samples.fragments_per_gene"
            outputDir:
                source: outputDir
                valueFrom: $(self + '/fragments_per_gene')
        out: [outputTable, outputDir]
        run: ../../tools/collect-columns_v1_0_0.cwl
    flatOutputDir:
        in:
            inputData:
                - HTSeqCount/outputDir
                - collectCounts/outputDir
        out: [flatArray]
        run: ../../tools/array_flatten.cwl
    # TODO: Expand workflow to cover when detectNovelTranscripts is true