cwlVersion: v1.2
class: Workflow
label: "Expression Quantification Workflow"
doc: "A CWL workflow that performs expression quantification, currently only with HTSeq Count."

inputs:
    bamFiles:
        type: File[]
        doc: "The input BAM files."
    referenceGtf:
        type: File
        doc: "A GTF/GFF file containing the features of interest."
    detectNovelTranscripts:
        type: boolean
        doc: "If true, generates a new GTF from BAM files using StringTie. When a reference GTF is provided, it guides the assembly."
    outputDir:
        type: string
        default: "."
        doc: "The output directory."

outputs:
    outputDir:
        type: Directory?
        outputSource:
            - HTSeqCount/outputDir
        doc: "The output directory."
    outputTable:
        type: File?
        outputSource: 
            - HTSeqCount/counts
        doc: "Read count table generated by HTSeq."

requirements:
    InlineJavascriptRequirement: {}

steps:
    HTSeqCount:
        in:
            inputBams: bamFiles
            gtfFile: referenceGtf
            outputDir: outputDir
        out: [counts, outputDir]
        run: ../../tools/htseq-count_v2_0_9.cwl
        when: $(!inputs.detectNovelTranscripts) 
    # TODO: Expand workflow to cover when detectNovelTranscripts is true