#!/bin/bash
# ===================================================================
# Script: compare_workflow_outputs.sh
# Purpose:
#   Compare output files generated by two bioinformatics workflows:
#     - CWL workflow (0X_CWL)
#     - WDL workflow (01_BioWDL)
#   Collect BAM statistics, FastQC outputs, and Cutadapt reports
#   Generate a diff summary of identical, different, or missing files.
# ===================================================================

set -euo pipefail  # Exit on error, unset variables, and pipe failures

# -----------------------
# Configuration
# -----------------------
cwl="../../0X_CWL"                     # CWL workflow output directory
wdl="../../01_BioWDL"                  # WDL workflow output directory
path="tmp/diff_files"                  # Directory to collect standardized outputs
diffdir="tmp/diff_files_diff"          # Directory for diff files
summary="diff_summary.txt"             # Summary report of comparisons

# Create directories if they do not exist
mkdir -p "$path/CWL" "$path/WDL" "$diffdir"

# Initialize summary file
: > "$summary"

# -----------------------
# Functions
# -----------------------

# detect_stage_bam: Determine the processing stage of a BAM file
detect_stage_bam() {
    local bam="$1"
    case "$bam" in
        *dedup.markdup*) echo "dedup.markdup" ;;
        *dedup*)        echo "dedup" ;;
        *markdup*)      echo "markdup" ;;
        *star*)         echo "star" ;;
        *)              echo "unknown" ;;
    esac
}

# detect_stage_fastqc: Determine the stage from a FastQC zip filename
detect_stage_fastqc() {
    local name="$1"
    case "$name" in
        *cutadapt*R1*fastqc.zip) echo "cut_read1" ;;
        *cutadapt*R2*fastqc.zip) echo "cut_read2" ;;
        *R1*fastqc.zip)          echo "read1" ;;
        *R2*fastqc.zip)          echo "read2" ;;
        *)                        echo "unknown" ;;
    esac
}

# detect_stage_cutadapt: Determine if file is a cutadapt report
detect_stage_cutadapt() {
    local name="$1"
    [[ "$name" == *cutadapt_report.txt* ]] && echo "cutadapt" || echo "unknown"
}

# process_files: Standardize outputs from BAM, FastQC, and Cutadapt reports
process_files() {
    local base="$1"     # base sample directory
    local outdir="$2"   # CWL or WDL output subdirectory
    local sample=$(basename "$base")

    # -----------------------
    # Process BAM files
    # -----------------------
    for bam in "$base"/lib_lib--rg_rg/*.bam \
               "$base"/*.dedup.markdup.bam \
               "$base"/*.dedup.bam \
               "$base"/*[0-9].markdup.bam; do
        [ -f "$bam" ] || continue
        stage=$(detect_stage_bam "$bam")
        outfile="$path/$outdir/${sample}_${stage}.flagstat"
        if [[ ! -f "$outfile" ]]; then
            echo "[$(date)] Flagstatting $bam → $outfile"
            samtools flagstat "$bam" > "$outfile"
        else
            echo "[$(date)] $outfile already exists!"
        fi
    done

    # -----------------------
    # Process FastQC reports
    # -----------------------
    for zipped in "$base"/lib_lib--rg_rg/*_fastqc.zip; do
        [ -f "$zipped" ] || continue
        name=$(basename "$zipped")
        stage=$(detect_stage_fastqc "$name")
        outfile="$path/$outdir/${sample}_${stage}.fastqc_data.txt"
        if [[ ! -f "$outfile" ]]; then
            echo "[$(date)] Extracting $stage FastQC data from $zipped → $outfile"
            unzip -p "$zipped" */fastqc_data.txt > "$outfile"
        else
            echo "[$(date)] $outfile already exists!"
        fi
    done

    # -----------------------
    # Process Cutadapt reports
    # -----------------------
    for cutrep in "$base"/lib_lib--rg_rg/*_cutadapt_report.txt; do
        [ -f "$cutrep" ] || continue
        name=$(basename "$cutrep")
        stage=$(detect_stage_cutadapt "$name")
        outfile="$path/$outdir/${sample}_${stage}.txt"
        if [[ ! -f "$outfile" ]]; then
            echo "[$(date)] Copying $stage data from $cutrep → $outfile"
            tail -n +6 "$cutrep" > "$outfile"
        else
            echo "[$(date)] $outfile already exists!"
        fi
    done
}

# normalize_name: Remove workflow-specific suffixes for comparison
normalize_name() {
    echo "$1" | sed -E 's/\.star\.?Aligned//; s/\.flagstat$//'
}

# extract_sample: Extract base sample name from standardized file
extract_sample() {
    local name="$1"
    name="${name%.flagstat}"
    echo "$name" | sed -E 's/-lib-rg\.star\.?Aligned.*//; s/-lib-rg\.sortedByCoord\.out//; s/\.dedup\.markdup//; s/\.dedup//; s/\.markdup//; s/\.fragments_per_gene//'
}

# extract_stage: Determine stage from standardized file name
extract_stage() {
    local name="$1"
    case "$name" in
        *cut_read1*) echo "cut_read1" ;;
        *cut_read2*) echo "cut_read2" ;;
        *read1*)     echo "read1" ;;
        *read2*)     echo "read2" ;;
        *cutadapt*)  echo "cutadapt" ;;
        *dedup.markdup*) echo "dedup.markdup" ;;
        *dedup*)     echo "dedup" ;;
        *markdup*)   echo "markdup" ;;
        *star*)      echo "star" ;;
        *fragments_per_gene*) echo "count_table" ;;
        *) echo "unknown" ;;
    esac
}

# stage_rank: Assign numeric rank to stage for sorting purposes
stage_rank() {
    case "$1" in
        read1) echo 00 ;;
        read2) echo 01 ;;
        cutadapt) echo 02 ;;
        cut_read1) echo 03 ;;
        cut_read2) echo 04 ;;
        star) echo 05 ;;
        markdup) echo 06 ;;
        dedup) echo 07 ;;
        dedup.markdup) echo 08 ;;
        count_table) echo 09 ;;
        *) echo 99 ;;
    esac
}

# compare_dirs: Compare two directories and produce summary of identical/different/missing files
# Parameters:
#   $1 = directory with WDL outputs
#   $2 = directory with CWL outputs
#   $3 = optional pattern to skip (e.g., "*all_samples*")
compare_dirs() {
    local wdl_dir="$1"
    local cwl_dir="$2"
    local skip_pattern="${3:-}"

    for stat in "$wdl_dir"/*; do
        [ -f "$stat" ] || continue
        base_wdl=$(basename "$stat")
        
        # Skip files matching pattern
        [[ -n "$skip_pattern" && "$base_wdl" == $skip_pattern ]] && continue

        key_wdl=$(normalize_name "$base_wdl")
        match_found=false

        for cwl_stat in "$cwl_dir"/*; do
            base_cwl=$(basename "$cwl_stat")
            key_cwl=$(normalize_name "$base_cwl")
            if [[ "$key_wdl" == "$key_cwl" ]]; then
                diff_file="$diffdir/${key_wdl}.diff"
                if diff "$stat" "$cwl_stat" > "$diff_file"; then
                    status="IDENTICAL"
                else
                    status="DIFFERENT"
                fi
                sample=$(extract_sample "$base_wdl")
                stage=$(extract_stage "$base_wdl")
                echo "$sample $stage $status" >> "$summary"
                match_found=true
                break
            fi
        done

        if [[ "$match_found" == false ]]; then
            sample=$(extract_sample "$base_wdl")
            stage=$(extract_stage "$base_wdl")
            echo "$sample $stage MISSING in CWL" >> "$summary"
        fi
    done
}

# -----------------------
# Main Execution
# -----------------------

# Process all samples in CWL and WDL directories
for base in "$cwl/samples/"* "$wdl/samples/"*; do
    outdir="CWL"
    [[ "$base" == *$cwl* ]] && outdir="CWL" || outdir="WDL"
    process_files "$base" "$outdir"
done

# Compare standardized outputs and generate summary
compare_dirs "$path/WDL" "$path/CWL"                                  # BAM/FastQC/Cutadapt
compare_dirs "$wdl/expression_measures/fragments_per_gene" \
             "$cwl/expression_measures/fragments_per_gene" "*all_samples*"  # Skip combined table

# -----------------------
# Sort summary file
# -----------------------
tmp="${summary}.sorted"
while read -r sample stage status; do
    rank=$(stage_rank "$stage")
    base_sample=${sample%%_*}
    echo "$base_sample $rank $stage $status"
done < "$summary" \
| sort -k1,1 -k2,2n \
| awk '{print $1, $3, $4}' \
> "$tmp"

mv "$tmp" "$summary"